app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
# src/Blog/AppBundle/Resources/config/routing.yml

index:
    pattern: /index
    defaults: { _controller: AppBundle:Post:index }

new_post:
    pattern: /new/post
    defaults: { _controller: AppBundle:Post:new }
    
# src/User/AppBundle/Resources/config/routing.yml

login:
    pattern: /login
    defaults: { _controller: AppBundle:Login:login }
    
login_check:
    pattern: /login_check
    defaults: { _controller: AppBundle:Login:loginCheck }
    
logout:
    pattern: /logout
    defaults: { _controller: AppBundle:Login:logout }
    
edit_post:
    pattern: /edit/post/{id_post}
    defaults: { _controller: AppBundle:Post:edit }
    
edit_comment:
    pattern: /edit/comment/{id_comment}
    defaults: { _controller: AppBundle:Comment:edit }
    
new_comment:
    pattern: /new/comment
    defaults: { _controller: AppBundle:Comment:new }