app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
# src/Blog/AppBundle/Resources/config/routing.yml

index:
    path: /{_locale}
    defaults: { _controller: AppBundle:Post:index, _locale: 'en' }
    requirements:
        _locale: en|fr|de

new_post:
    path: /new/post
    defaults: { _controller: AppBundle:Post:new }

about:
    path: /blog/about
    defaults: { _controller: AppBundle:Blog:about }

contact:
    path: /blog/contact
    defaults: { _controller: AppBundle:Blog:contact }
    
# src/User/AppBundle/Resources/config/routing.yml

login:
    path: /login
    defaults: { _controller: AppBundle:Login:login }
    
login_check:
    path: /login_check
    defaults: { _controller: AppBundle:Login:loginCheck }
    
logout:
    path: /logout
    defaults: { _controller: AppBundle:Login:logout }
    
edit_post:
    path: /edit/post/{id}
    defaults: { _controller: AppBundle:Post:edit }
    
edit_comment:
    path: /edit/comment/{id}
    defaults: { _controller: AppBundle:Comment:edit }
    
new_comment:
    path: /new/comment/{id_post}
    defaults: { _controller: AppBundle:Comment:new }